### ISSUE TITLE
How to specify the state of traffic lights in the scenario?

### ISSUE THREAD

**Issue by hcn1519** [tier4/scenario_simulator_v2#1236]
I am running a scenario using the scenario test runner, and I wonder how to specify the state of traffic lights in the [TIER IV Scenario Format Version 2.0](https://tier4.github.io/scenario_simulator_v2-docs/developer_guide/TIERIVScenarioFormatVersion2/). It seems that the scenario simulator v2 does not follow the [OpenScenario v1.2 specification](https://publications.pages.asam.net/standards/ASAM_OpenSCENARIO/ASAM_OpenSCENARIO_XML/v1.2.0/10_scenario_creation/10_10_traffic_signal.html).

Below are my scenario and map files, which I used to test traffic light behaviors. The scenario includes a simple ego routing story and sets all traffic lights to red. (I have checked the syntax against [other scenario files](https://github.com/tier4/scenario_simulator_v2/blob/2dbab8a177ea0b02323f8022f60c276238536bc7/test_runner/scenario_test_runner/scenario/CustomCommandAction.V2ITrafficSignalStateAction.yaml), though there might be an error.) I expected the ego car to stop at the junction because of the traffic light, but it ignores it and reaches the destination.

- [test_scenario_map.zip](https://github.com/tier4/scenario_simulator_v2/files/15056119/test_scenario_map.zip)

The code below is the part related to traffic lights in the scenario file.

```yaml
RoadNetwork:
  LogicFile:
    filepath: lanelet2_map.osm
  SceneGraphFile:
    filepath: point_cloud.pcd
  TrafficSignals:
      TrafficSignalController:
      - name: test_signals
        Phase:
        - duration: INF
          name: Stop
          TrafficSignalState:
          - state: red solidOn circle
            trafficSignalId: '494'
          - state: red solidOn circle
            trafficSignalId: '520'
          - state: red solidOn circle
            trafficSignalId: '586'
          - state: red solidOn circle
            trafficSignalId: '553'
Storyboard:
    Init:
      Actions:
        GlobalAction:
        - InfrastructureAction:
            TrafficSignalAction:
              TrafficSignalControllerAction:
                phase: Stop
                trafficSignalControllerRef: test_signals
```
