### ISSUE TITLE
Scenario simulator does not print or visualize parameters/modifier used for test iterations

### ISSUE THREAD

**Issue by ahmeddesokyebrahim** [tier4/scenario_simulator_v2#1272]
**Is your feature request related to a problem? Please describe.**
While debugging scenarios with different values (list) for modifiers, it is not clear which values is selected and used between different combinations in a specific test iteration.

For example, a scenario with modifiers like that ...
```
    - name: __tier4_modifier_an
      list:
        - 0.2
        - 2
    - name: __tier4_modifier_D
      list:
        - 5
        - 10
```  
it becomes confusing which values of `__tier4_modifier_an` is used with which value of ` __tier4_modifier_D` in an iteration

**Describe the solution you'd like**
It will be helpful if the parameters and modifiers used for each iteration is visualized in RViz.

**Describe alternatives you've considered**
It could a valid alternative to have it only printed in the terminal instead of text visualization in RViz

**Additional context**
